export const TELLER_CASH_RECEIVE_ACTIVITY_CODE = 101;
export const TELLER_CASH_WITHDRAW_ACTIVITY_CODE = 102;
export const TELLER_CASH_TRANSFER_ACTIVITY_CODE = 103;

export const TELLER_TP_VIOLATION_CODE = 2310005;